import pytest
from lazebot import game_data
from lazebot.game_data import Unit
from lazebot import swgohgg
from lazebot.api_cache_file import ApiCacheFile


def test_fetch():
    (guild_name, players, guild_units) = game_data.fetch_players_and_guild_units(
        "736645715", {"BOBAFETTSCION", "TIEINTERCEPTOR"})
    assert guild_name == "ClanBeroya"
    assert len(players) == 50
    assert players["736645715"].allyCode == "736645715"
    assert players["736645715"].name == "Laze Bastra"
    assert players["736645715"].units == [
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='736645715', owner='Laze Bastra'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7,
             ship=True, allyCode='736645715', owner='Laze Bastra')
    ]
    assert guild_units == {'TIEINTERCEPTOR': [
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=5, ship=True,
             allyCode='385214597', owner='TwöHearted'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='157957918', owner='MINIFrothy Walrus'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='894491986', owner='Rap Digo'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='872319537', owner='Fatesshadow'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='699418728', owner='Shoiti'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='738733632', owner='Old Maath'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='446346384', owner='The WerePizza'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='441392819', owner='Zula Wren'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='124386395', owner='KeşPanda'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='463984383', owner='fuzzypickles'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='468277145', owner='IndySteve'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='559873813', owner='Papaofmom'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='867284984', owner='PeJah91'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='736645715', owner='Laze Bastra'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='749836178', owner='DarthTurin'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='834194725', owner='DaHa'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='469438919', owner='CatMasters'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='545547414', owner='Sκγ βεήdέr Unleashed'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='242848755', owner='Δχέ ωΦνέș'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='796382821', owner='Mushima'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='138488913', owner='Caokeo'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='673983664', owner='Benloc0'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='989957716', owner='TajTheRock'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='734139688', owner='Azrael'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='373616324', owner='GrandAdmiralWicket'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='367558926', owner='Ozzy20'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='315636959', owner='Elros Elendae'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='227854852', owner='I have iced tea'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='428938971', owner='Jonnovision'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='787125778', owner='SŇydeR'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=6, ship=True,
             allyCode='173472829', owner='Fulcrum Unleashed'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='839465738', owner='Hero of Narth'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='394849534', owner='theOne X'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='513252419', owner='Xerxo Bodrun'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='113348231', owner='Cheesecakehunter'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='129481921', owner='The Hermit'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='498636777', owner='Alphaconn'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='889253239', owner='Bao Dur'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='387674373', owner='Carl'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='524218147', owner='Därth Bënji'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='779751657', owner='This is the way'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='945966261', owner='Bail'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='138862254', owner='Arcann'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='317353364', owner='Aquafit'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='269812363', owner='Owio'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=6, ship=True,
             allyCode='462362841', owner='Rfox'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='771747668', owner='E0351'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='142711953', owner='Mini Bdogg'),
        Unit(baseId='TIEINTERCEPTOR', name='TIE/IN Interceptor Prototype', gear=1, relic=-1, rarity=7, ship=True,
             allyCode='244352453', owner='WoSR')], 'BOBAFETTSCION': [
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=12, relic=-1, rarity=7, ship=False,
             allyCode='385214597', owner='TwöHearted'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='157957918', owner='MINIFrothy Walrus'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=12, relic=-1, rarity=7, ship=False,
             allyCode='894491986', owner='Rap Digo'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='872319537', owner='Fatesshadow'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=7, rarity=7, ship=False,
             allyCode='699418728', owner='Shoiti'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=12, relic=-1, rarity=7, ship=False,
             allyCode='738733632', owner='Old Maath'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=7, rarity=7, ship=False,
             allyCode='446346384', owner='The WerePizza'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=8, relic=-1, rarity=7, ship=False,
             allyCode='441392819', owner='Zula Wren'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=7, rarity=7, ship=False,
             allyCode='124386395', owner='KeşPanda'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=10, relic=-1, rarity=7, ship=False,
             allyCode='463984383', owner='fuzzypickles'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=3, rarity=7, ship=False,
             allyCode='468277145', owner='IndySteve'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=6, rarity=7, ship=False,
             allyCode='559873813', owner='Papaofmom'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=12, relic=-1, rarity=7, ship=False,
             allyCode='867284984', owner='PeJah91'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='736645715', owner='Laze Bastra'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=7, rarity=7, ship=False,
             allyCode='749836178', owner='DarthTurin'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=8, relic=-1, rarity=7, ship=False,
             allyCode='834194725', owner='DaHa'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=7, rarity=7, ship=False,
             allyCode='469438919', owner='CatMasters'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='545547414', owner='Sκγ βεήdέr Unleashed'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=8, rarity=7, ship=False,
             allyCode='242848755', owner='Δχέ ωΦνέș'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='989957716', owner='TajTheRock'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=7, rarity=7, ship=False,
             allyCode='373616324', owner='GrandAdmiralWicket'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=8, rarity=7, ship=False,
             allyCode='367558926', owner='Ozzy20'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=10, relic=-1, rarity=7, ship=False,
             allyCode='315636959', owner='Elros Elendae'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='428938971', owner='Jonnovision'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=6, rarity=7, ship=False,
             allyCode='787125778', owner='SŇydeR'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=1, rarity=7, ship=False,
             allyCode='173472829', owner='Fulcrum Unleashed'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=8, relic=-1, rarity=7, ship=False,
             allyCode='839465738', owner='Hero of Narth'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='394849534', owner='theOne X'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='513252419', owner='Xerxo Bodrun'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=1, rarity=7, ship=False,
             allyCode='113348231', owner='Cheesecakehunter'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='129481921', owner='The Hermit'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='498636777', owner='Alphaconn'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=8, rarity=7, ship=False,
             allyCode='889253239', owner='Bao Dur'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=10, relic=-1, rarity=7, ship=False,
             allyCode='387674373', owner='Carl'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=8, rarity=7, ship=False,
             allyCode='524218147', owner='Därth Bënji'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='945966261', owner='Bail'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=12, relic=-1, rarity=7, ship=False,
             allyCode='138862254', owner='Arcann'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=1, relic=-1, rarity=7, ship=False,
             allyCode='317353364', owner='Aquafit'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=8, relic=-1, rarity=7, ship=False,
             allyCode='152668344', owner='laitea'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=8, relic=-1, rarity=7, ship=False,
             allyCode='269812363', owner='Owio'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=0, rarity=7, ship=False,
             allyCode='771747668', owner='E0351'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=8, relic=-1, rarity=7, ship=False,
             allyCode='142711953', owner='Mini Bdogg'),
        Unit(baseId='BOBAFETTSCION', name='Boba Fett, Scion of Jango', gear=13, relic=5, rarity=7, ship=False,
             allyCode='244352453', owner='WoSR')
    ]}
    assert True
